[package]
name = "cls"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
hound = "3.5.1"
rand = "0.8.5"
rodio = "0.19.0"
serde = { version = "1.0.214", features = ["derive"] }
serde-lexpr = "0.1.3"
thiserror = "2.0.0"
